# Generated by Django 5.1.1 on 2025-10-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxupload',
            name='zip_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
