# Generated by Django 5.1.1 on 2025-10-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dropboxupload_zip_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxupload',
            name='dropbox_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dropboxupload',
            name='dropbox_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
