# Generated by Django 5.2.6 on 2025-10-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('dropbox_path', models.CharField(max_length=255)),
                ('dropbox_link', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
