# Generated by Django 5.2.6 on 2025-10-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dropboxupload_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxupload',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
