# Generated by Django 5.1.1 on 2025-10-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dropboxupload_dropbox_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unlimited_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='video_credits',
            field=models.IntegerField(default=0),
        ),
    ]
