# Generated by Django 5.2.6 on 2025-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dropboxupload_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxupload',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dropboxupload',
            name='transcription_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
