# Generated by Django 5.1.1 on 2025-10-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_unlimited_uploads_user_video_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unlimited_uploads',
        ),
    ]
