# Generated by Django 5.2.6 on 2025-10-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dropboxupload_transcript_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxupload',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
